GUI/ITFest/ITFest/Models/AcceptedReservations.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ITFest.Models
{
    public class AcceptedReservations
    {

        [Display(Name = "Start Date Filter")]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public DateTime StartDateFilter { get; set; }

        [Display(Name = "End Date Filter")]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy hh:mm tt}", ApplyFormatInEditMode = true)]
        public DateTime EndDateFilter { get; set; }

        public List<Reservation> MyReservations { get; set; }
    }
}

GUI/ITFest/ITFest/Models/Reservation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Newtonsoft.Json;

namespace ITFest.Models
{
    public class Reservation
    {

        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        [JsonProperty(PropertyName = "date")]
        public DateTime? Date { get; set; }

        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        [JsonProperty(PropertyName = "message")]
        public string Message { get; set; }

        [JsonProperty(PropertyName = "name")]
        public string Owner { get; set; }

        [JsonProperty(PropertyName = "no_people")]
        public int? NrOfPersons { get; set; }

        public bool? Status { get; set; }

        [JsonProperty(PropertyName = "insertion_time")]
        public DateTime? StartReservationDate { get; set; }
        [JsonProperty(PropertyName = "expiration_time")]
        public DateTime? EndReservationDate { get; set; }

        [JsonProperty(PropertyName = "prefferences")]
        public string Prefferences { get; set; }

        [JsonProperty(PropertyName = "emotion")]
        public string Emotion { get; set; }


        public int? NrOfFreeSpaces { get; set; }
        public int TableNumber { get; set; }
        public string TableLink { get; set; }

        public string StartToString { get; set; }
        public string EndToString { get; set; }

    }
}

GUI/ITFest/ITFest/Controllers/ReservationController.cs
using ITFest.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Threading.Tasks;
using ITFest.Models;
namespace ITFest.Controllers
{
    public class ReservationController : Controller
    {
        [ActionName("Index")]
        public async Task<ActionResult> IndexAsync()
        {     
            var reservations = await DocumentDBRepository<Reservation>.GetItemsAsync();

            var resList = CalculateEndTime(reservations);

            return View(reservations);
        }

        [ActionName("AcceptedReservations")]
        public async Task<ActionResult> AcceptedReservationsAsync()
        {
            var myRes = await DocumentDBRepository<Reservation>.GetItemsAsync();

            var myResList = myRes.ToList();

            if (myResList.Count > 0 && myResList != null)
            {
                myResList.Where(x => x.Status == true);
            }

            AcceptedReservations myAcceptedReservations = new AcceptedReservations();

            myAcceptedReservations.MyReservations = myResList.ToList();
            myAcceptedReservations.StartDateFilter = DateTime.Now;
            myAcceptedReservations.EndDateFilter = DateTime.Now;

            return View(myAcceptedReservations);
        }

        [HttpPost]
        public async Task<ActionResult> FilterReservations(DateTime StartDateTime, DateTime EndDateTime)
        {
            var myRes = await DocumentDBRepository<Reservation>.GetItemsAsync();

            var myResList = CalculateEndTime(myRes);

            List<Reservation> mySecondList = new List<Reservation>();

            foreach (var x in myResList)
            {
                x.StartToString = x.Date.ToString();
                x.EndToString = x.EndReservationDate.ToString();

                bool hasEarlyStartDat = false;
                bool hasLaterEndDate = false;


                if (x.Date.HasValue)
                {
                    var Date = Convert.ToDateTime(x.Date);
                    if(DateTime.Compare(Date, StartDateTime) >= 0)
                    {
                        hasEarlyStartDat = true;
                    }
                }

                if (x.EndReservationDate.HasValue)
                {
                    var EndReservationDate = Convert.ToDateTime(x.EndReservationDate);
                    if (DateTime.Compare(EndReservationDate, EndDateTime) < 0)
                    {
                        hasLaterEndDate = true;
                    }
                }

                if (hasEarlyStartDat == true && hasLaterEndDate == true)
                {
                    mySecondList.Add(x);
                }
            }


            return Json(mySecondList);
        }

        [ActionName("GetDetails")]
        public async Task<ActionResult> GetDetails(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Reservation item = await DocumentDBRepository<Reservation>.GetItemAsync(id);
            if (item == null)
            {
                return HttpNotFound();
            }

            if (item.EndReservationDate.HasValue == false)
            {
                double clientStayingTime = Math.Sqrt(Convert.ToInt64(item.NrOfPersons));
                clientStayingTime = Convert.ToInt32(clientStayingTime);

                var hours = Convert.ToInt32(clientStayingTime);


                if (hours + item.Date.Value.Hour > 24)
                {
                    item.EndReservationDate = new DateTime(item.Date.Value.Year,
                        item.Date.Value.Month,
                        item.Date.Value.Day,
                        Math.Abs(24 - hours),
                        item.Date.Value.Minute,
                        item.Date.Value.Second);
                    item.EndReservationDate.Value.AddDays(1);
                }
                else if (hours + item.Date.Value.Hour < 24)
                {
                    item.EndReservationDate = new DateTime(item.Date.Value.Year,
                        item.Date.Value.Month,
                        item.Date.Value.Day,
                        item.Date.Value.Hour + hours,
                        item.Date.Value.Minute,
                        item.Date.Value.Second);
                }
                else if (hours + item.Date.Value.Hour == 24)
                {
                    item.EndReservationDate = new DateTime(item.Date.Value.Year,
                     item.Date.Value.Month,
                     item.Date.Value.Day,
                     0,
                     item.Date.Value.Minute,
                     item.Date.Value.Second);
                    item.EndReservationDate.Value.AddDays(1);
                }
            }

            return View(item);
        }

        public List<Reservation> CalculateEndTime(IEnumerable<Reservation> reservations)
        {
            foreach (var res in reservations)
            {
                if (res.EndReservationDate.HasValue == false)
                {
                    double clientStayingTime = Math.Sqrt(Convert.ToInt64(res.NrOfPersons));
                    clientStayingTime = Convert.ToInt32(clientStayingTime);

                    var hours = Convert.ToInt32(clientStayingTime);


                    if (hours + res.Date.Value.Hour > 24)
                    {
                        res.EndReservationDate = new DateTime(res.Date.Value.Year,
                            res.Date.Value.Month,
                            res.Date.Value.Day,
                            Math.Abs(24 - hours),
                            res.Date.Value.Minute,
                            res.Date.Value.Second);
                        res.EndReservationDate.Value.AddDays(1);
                    }
                    else if (hours + res.Date.Value.Hour < 24)
                    {
                        res.EndReservationDate = new DateTime(res.Date.Value.Year,
                            res.Date.Value.Month,
                            res.Date.Value.Day,
                            res.Date.Value.Hour + hours,
                            res.Date.Value.Minute,
                            res.Date.Value.Second);
                    }
                    else if(hours + res.Date.Value.Hour == 24)
                    {
                        res.EndReservationDate = new DateTime(res.Date.Value.Year,
                         res.Date.Value.Month,
                         res.Date.Value.Day,
                         0,
                         res.Date.Value.Minute,
                         res.Date.Value.Second);
                         res.EndReservationDate.Value.AddDays(1);
                    }
                }
            }
            return reservations.ToList();
        }


        //[HttpPost]
        //[ActionName("Edit")]
        //[ValidateAntiForgeryToken]
        //public async Task<ActionResult> EditAsync()
        //{
        //    //iau toate inregistrarile
        //    var myRes = await DocumentDBRepository<Reservation>.GetItemsAsync();

        //    //numarul total de 
        //    int TotalNumberOfFreeSpaces = 80;

        //    var myResList = myRes.ToList();
        //    myResList.OrderBy(x => x.Date);
        //    List<Reservation> myNewResList = new List<Reservation>();

        //    foreach (var x in myResList)
        //    {
        //        bool isOK = true;

        //        foreach (var y in myNewResList)
        //        {
        //            if (DateTime.Compare())
        //        }
        //    }

        //    //pt fiecare inregistrare
        //    foreach (var res in myRes)
        //    {
        //        if (res.EndReservationDate.HasValue == false)
        //        {
        //            double clientStayingTime = Math.Sqrt(Convert.ToInt64(res.NrOfPersons));
        //            clientStayingTime = Convert.ToInt32(clientStayingTime);

        //            var hours = Convert.ToInt32(clientStayingTime / 60);
        //            var minutes = Convert.ToInt32(clientStayingTime - hours * 60);
        //            if (res.Status == null)
        //            {
        //                res.EndReservationDate = new DateTime(res.Date.Value.Year, res.Date.Value.Month, res.Date.Value.Day, res.Date.Value.Day, res.Date.Value.Hour + hours, res.Date.Value.Minute + minutes);
        //                if (TotalNumberOfFreeSpaces >= res.NrOfPersons)
        //                {
        //                    //1 = acceptata
        //                    res.Status = 1;
        //                    TotalNumberOfFreeSpaces -= Convert.ToInt32(res.NrOfPersons);
        //                }
        //                else if (TotalNumberOfFreeSpaces < res.NrOfPersons)
        //                {
        //                    //2 = refuzata
        //                    res.Status = 2;
        //                }
        //            }
        //            //timpul de expirare a rezervarii e > data si timpul curent
        //            else if (res.Status == 1 && DateTime.Compare(Convert.ToDateTime(res.EndReservationDate), DateTime.Now) <= 0)
        //            {
        //                //a trecut timpul rezervarii, posibil ca oamenii sa fi fost sau nu la masa
        //                res.Status = 3;
        //                TotalNumberOfFreeSpaces += Convert.ToInt32(res.NrOfPersons);
        //            }
        //        }



        //        ///

        //        //foreach (var res in myResList)
        //        //{
        //        //    if()
        //        //    await DocumentDBRepository<Reservation>.UpdateItemAsync(item.Id, item);

        //        //}


        //        return RedirectToAction("Index");

        //    }

        }
    }

GUI/ITFest/ITFest/Views/Reservation/AcceptedReservations.cshtml
@model ITFest.Models.AcceptedReservations

@{
    ViewBag.Title = "AcceptedReservations";
}

<h2>Accepted Reservations Preview</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.StartDateFilter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StartDateFilter, new { htmlAttributes = new { Value = Model.StartDateFilter.ToString("dd-MMM-yyyy hh:mm tt"), @class = "form-control date-picker onChangeEvents", onkeydown = "return false", onpaste = "return false" } })
                @Html.ValidationMessageFor(model => model.StartDateFilter, "", new { @class = "text-danger" })
            </div>
        </div>

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EndDateFilter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EndDateFilter, new { htmlAttributes = new { Value = Model.EndDateFilter.ToString("dd-MMM-yyyy hh:mm tt"), @class = "form-control date-picker onChangeEvents", onkeydown = "return false", onpaste = "return false" } })
                @Html.ValidationMessageFor(model => model.StartDateFilter, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>
}
<br />


<div id="displayElements">

</div>


@Html.ActionLink("Back", "Index", "Home", htmlAttributes: new { @class = "btn btn-info" })

<script src="~/Scripts/jquery-3.2.1.min.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.min.js"></script>
<script src="~/Scripts/jquery-ui-timepicker-addon.min.js"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $(".date-picker").datetimepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: "-100:+0",
                dateFormat: 'dd-M-yy',
                controlType: 'select',
                timeFormat: 'hh:mm TT'
            });
        });
    });

    $(".onChangeEvents").on('change', function (ev) {

        var StartDateTime = $("#StartDateFilter").val();
        var EndDateTime = $("#EndDateFilter").val();
        $("#displayElements").empty();

        ev.preventDefault();
        $.ajax({
            type: "POST",
            url: '@Url.Action("FilterReservations", "Reservation")',
            dataType: "json",
            data: {
                StartDateTime: StartDateTime,
                EndDateTime: EndDateTime
            },
            success: function (data) {

                var htmlString = '';
                var Src = "~/Content/Images/table.jpg";
                for (var i = 0; i < data.length; i++)

                htmlString += '<div class="Tables">' +
                        '<a href="/Reservation/GetDetails/' + data[i].Id + '">' +
                        '<img src="@Url.Content(String.Format("{0}", "~/Content/Images/table.jpg"))" class="tablePic"/>' +
                        '</a >' + 
                        '<p>Nume: ' + data[i].Owner + '</p>' +
                        '<p>Number of persons: ' + data[i].NrOfPersons + '</p>' +
                        '<p>Start reservation time: ' + data[i].StartToString + '</p>' +
                        '<p>End reservation time: ' + data[i].EndToString + '</p>' +
                        '</div>';

                    $('#displayElements').append(htmlString);


            },
            error: function () {
                alert('An error occurred, please try again');
            }
        });

    });

</script>

GUI/ITFest/ITFest/Views/Reservation/GetDetails.cshtml
@model ITFest.Models.Reservation
@{
    ViewBag.Title = "GetDetails";
}

<h2>Details For Reservation on @Model.Date</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Owner</th>
            <th scope="col">Number of persons</th>
            <th scope="col">Email</th>
            <th scope="col">Message</th>
            <th scope="col">Reservation Start Date</th>
            <th scope="col">Reservation End Date</th>
            <th scope="col">Prefferences</th>
            <th scope="col">Emotions</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.Date</td>
            <td>@Model.Owner</td>
            <td>@Model.NrOfPersons</td>
            <td>@Model.Email</td>
            <td>@Model.Message</td>
            <td>@Model.Date</td>
            <td>@Model.EndReservationDate</td>
            <td>@Model.Prefferences</td>
            <td>@Model.Emotion</td>
        </tr>
    </tbody>
</table>


@Html.ActionLink("Index", "Index", "Home", htmlAttributes: new { @class = "btn btn-info" })
<a class="btn btn-info" href="@Url.Action("AcceptedReservations")">Back to Accepted Reservations</a>

GUI/ITFest/ITFest/Views/Reservation/Index.cshtml
@model List<ITFest.Models.Reservation>
@{
    ViewBag.Title = "ReservationList";
}

<h2>Reservation List</h2>

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Date</th>
            <th scope="col">Owner</th>
            <th scope="col">Number of persons</th>
            <th scope="col">Email</th>
            <th scope="col">Message</th>
            <th scope="col">Reservation Start Date</th>
            <th scope="col">Reservation End Date</th>
            <th scope="col">Prefferences</th>
            <th scope="col">Emotions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var myRes in Model)
        {
            <tr>
                <td>@myRes.Date</td>
                <td>@myRes.Owner</td>
                <td>@myRes.NrOfPersons</td>
                <td>@myRes.Email</td>
                <td>@myRes.Message</td>
                <td>@myRes.Date</td>
                <td>@myRes.EndReservationDate</td>
                <td>@myRes.Prefferences</td>
                <td>@myRes.Emotion</td>
            </tr>
        }
    </tbody>
</table>



<a class="btn btn-info" href="@Url.Action("AcceptedReservations")">Check Accepted Reservations</a>